/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// PublicApiService is a service that implements the logic for the PublicApiServicer
// This service should implement the business logic for every endpoint for the PublicApi API.
// Include any external packages or services that will be required by this service.
type PublicApiService struct {
}

// NewPublicApiService creates a default api service
func NewPublicApiService() PublicApiServicer {
	return &PublicApiService{}
}

// GetCarouselItems - Get carousel items
func (s *PublicApiService) GetCarouselItems(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetCarouselItems with the required logic for this service method.
	// Add api_public_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []CarouselItem{}) or use other options such as http.Ok ...
	//return Response(200, []CarouselItem{}), nil

	//TODO: Uncomment the next line to return response Response(404, NotFoundError{}) or use other options such as http.Ok ...
	//return Response(404, NotFoundError{}), nil

	//TODO: Uncomment the next line to return response Response(0, InternalServerError{}) or use other options such as http.Ok ...
	//return Response(0, InternalServerError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCarouselItems method not implemented")
}

// GetLocation - Get location details
func (s *PublicApiService) GetLocation(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetLocation with the required logic for this service method.
	// Add api_public_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Location{}) or use other options such as http.Ok ...
	//return Response(200, Location{}), nil

	//TODO: Uncomment the next line to return response Response(404, NotFoundError{}) or use other options such as http.Ok ...
	//return Response(404, NotFoundError{}), nil

	//TODO: Uncomment the next line to return response Response(0, InternalServerError{}) or use other options such as http.Ok ...
	//return Response(0, InternalServerError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetLocation method not implemented")
}

// GetPageContents - Get page contents
func (s *PublicApiService) GetPageContents(ctx context.Context, pageId string) (ImplResponse, error) {
	// TODO - update GetPageContents with the required logic for this service method.
	// Add api_public_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []PageContent{}) or use other options such as http.Ok ...
	//return Response(200, []PageContent{}), nil

	//TODO: Uncomment the next line to return response Response(404, NotFoundError{}) or use other options such as http.Ok ...
	//return Response(404, NotFoundError{}), nil

	//TODO: Uncomment the next line to return response Response(0, InternalServerError{}) or use other options such as http.Ok ...
	//return Response(0, InternalServerError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetPageContents method not implemented")
}
