/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// UserManagementApiService is a service that implements the logic for the UserManagementApiServicer
// This service should implement the business logic for every endpoint for the UserManagementApi API.
// Include any external packages or services that will be required by this service.
type UserManagementApiService struct {
}

// NewUserManagementApiService creates a default api service
func NewUserManagementApiService() UserManagementApiServicer {
	return &UserManagementApiService{}
}

// GetUser - Provides user profile information
func (s *UserManagementApiService) GetUser(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetUser with the required logic for this service method.
	// Add api_user_management_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	//return Response(200, User{}), nil

	//TODO: Uncomment the next line to return response Response(401, UnauthorizedError{}) or use other options such as http.Ok ...
	//return Response(401, UnauthorizedError{}), nil

	//TODO: Uncomment the next line to return response Response(403, ForbiddenError{}) or use other options such as http.Ok ...
	//return Response(403, ForbiddenError{}), nil

	//TODO: Uncomment the next line to return response Response(404, NotFoundError{}) or use other options such as http.Ok ...
	//return Response(404, NotFoundError{}), nil

	//TODO: Uncomment the next line to return response Response(0, InternalServerError{}) or use other options such as http.Ok ...
	//return Response(0, InternalServerError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetUser method not implemented")
}
