/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PageContent struct {
	Html string `json:"html,omitempty"`
}

// AssertPageContentRequired checks if the required fields are not zero-ed
func AssertPageContentRequired(obj PageContent) error {
	return nil
}

// AssertRecursePageContentRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PageContent (e.g. [][]PageContent), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePageContentRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPageContent, ok := obj.(PageContent)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPageContentRequired(aPageContent)
	})
}
