/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserId struct {
	UserId string `json:"userId,omitempty"`
}

// AssertUserIdRequired checks if the required fields are not zero-ed
func AssertUserIdRequired(obj UserId) error {
	return nil
}

// AssertRecurseUserIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserId (e.g. [][]UserId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserId, ok := obj.(UserId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserIdRequired(aUserId)
	})
}
