/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AnnouncementId struct {
	Id string `json:"id"`
}

// AssertAnnouncementIdRequired checks if the required fields are not zero-ed
func AssertAnnouncementIdRequired(obj AnnouncementId) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAnnouncementIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AnnouncementId (e.g. [][]AnnouncementId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAnnouncementIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAnnouncementId, ok := obj.(AnnouncementId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAnnouncementIdRequired(aAnnouncementId)
	})
}
