/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InternalServerErrorErrors struct {
	Code int32 `json:"code"`

	Field string `json:"field"`

	Message string `json:"message"`
}

// AssertInternalServerErrorErrorsRequired checks if the required fields are not zero-ed
func AssertInternalServerErrorErrorsRequired(obj InternalServerErrorErrors) error {
	elements := map[string]interface{}{
		"code":    obj.Code,
		"field":   obj.Field,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseInternalServerErrorErrorsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InternalServerErrorErrors (e.g. [][]InternalServerErrorErrors), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInternalServerErrorErrorsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInternalServerErrorErrors, ok := obj.(InternalServerErrorErrors)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInternalServerErrorErrorsRequired(aInternalServerErrorErrors)
	})
}
