/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BackgroundImageItem struct {
	Id string `json:"id"`

	Src string `json:"src"`

	Width int32 `json:"width,omitempty"`

	Height int32 `json:"height,omitempty"`
}

// AssertBackgroundImageItemRequired checks if the required fields are not zero-ed
func AssertBackgroundImageItemRequired(obj BackgroundImageItem) error {
	elements := map[string]interface{}{
		"id":  obj.Id,
		"src": obj.Src,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseBackgroundImageItemRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BackgroundImageItem (e.g. [][]BackgroundImageItem), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBackgroundImageItemRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBackgroundImageItem, ok := obj.(BackgroundImageItem)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBackgroundImageItemRequired(aBackgroundImageItem)
	})
}
