/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FamilyId struct {
	FamilyId string `json:"familyId,omitempty"`
}

// AssertFamilyIdRequired checks if the required fields are not zero-ed
func AssertFamilyIdRequired(obj FamilyId) error {
	return nil
}

// AssertRecurseFamilyIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FamilyId (e.g. [][]FamilyId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFamilyIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFamilyId, ok := obj.(FamilyId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFamilyIdRequired(aFamilyId)
	})
}
