/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InternalServerError - Unhandled internal server error has occurred.
type InternalServerError struct {
	Message string `json:"message"`

	Code int32 `json:"code"`

	Errors []InternalServerErrorErrors `json:"errors,omitempty"`
}

// AssertInternalServerErrorRequired checks if the required fields are not zero-ed
func AssertInternalServerErrorRequired(obj InternalServerError) error {
	elements := map[string]interface{}{
		"message": obj.Message,
		"code":    obj.Code,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Errors {
		if err := AssertInternalServerErrorErrorsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseInternalServerErrorRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InternalServerError (e.g. [][]InternalServerError), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInternalServerErrorRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInternalServerError, ok := obj.(InternalServerError)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInternalServerErrorRequired(aInternalServerError)
	})
}
