/*
 * User Manager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserData struct {

	// A unique identifier
	Id string `json:"id,omitempty"`

	// Family ID to which user belongs to
	FamilyId string `json:"familyId,omitempty"`

	// Display name of the user
	DisplayName string `json:"displayName,omitempty"`

	// First name
	FirstName string `json:"firstName"`

	// Middle name
	MiddleName string `json:"middleName,omitempty"`

	// First name
	LastName string `json:"lastName"`

	// Baptismal Name
	BaptismalName string `json:"baptismalName,omitempty"`

	// House name
	HouseName string `json:"houseName,omitempty"`

	// Family unit
	FamilyUnit string `json:"familyUnit,omitempty"`

	// Date of birth
	DateOfBirth string `json:"dateOfBirth"`

	// Date of baptism
	DateOfBaptism string `json:"dateOfBaptism,omitempty"`

	// Date of confirmation
	DateOfConfirmation string `json:"dateOfConfirmation,omitempty"`

	// Date of marriage
	DateOfMarriage string `json:"dateOfMarriage,omitempty"`

	// Home parish
	HomeParish string `json:"homeParish,omitempty"`

	// Diocese in India
	DioceseInIndia string `json:"dioceseInIndia,omitempty"`

	// Previous Parish in Canada
	PreviousParishInCanada string `json:"previousParishInCanada,omitempty"`

	// Email ID of user
	Email string `json:"email"`

	// Indicates primary user
	IsPrimary bool `json:"isPrimary,omitempty"`

	// Gender
	Gender string `json:"gender"`

	Relation string `json:"relation,omitempty"`

	MaritalStatus string `json:"maritalStatus,omitempty"`

	// Apartment Number
	Apartment string `json:"apartment,omitempty"`

	// Street number and name
	Street string `json:"street,omitempty"`

	// City
	City string `json:"city,omitempty"`

	// Status in Canada
	CanadianStatus string `json:"canadianStatus,omitempty"`

	// In Canada since
	InCanadaSince string `json:"inCanadaSince,omitempty"`

	// Profession
	Profession string `json:"profession,omitempty"`

	// Province
	Province string `json:"province,omitempty"`

	// Postal Code
	PostalCode string `json:"postalCode,omitempty"`

	// Mobile number
	Mobile string `json:"mobile,omitempty"`
}

// AssertUserDataRequired checks if the required fields are not zero-ed
func AssertUserDataRequired(obj UserData) error {
	elements := map[string]interface{}{
		"firstName":   obj.FirstName,
		"lastName":    obj.LastName,
		"dateOfBirth": obj.DateOfBirth,
		"email":       obj.Email,
		"gender":      obj.Gender,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseUserDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserData (e.g. [][]UserData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserData, ok := obj.(UserData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserDataRequired(aUserData)
	})
}
