version: '3'

services:
  localstack:
    build:
      context: .
      dockerfile: Dockerfile.localstack
    image: usermanager_localstack
    container_name: usermanager_localstack
    ports:
      - "4567:4566"
    environment:
      - DYNAMODB_SHARE_DB=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts:/etc/localstack/init/ready.d/"

  dynamodb-gui:
    image: aaronshaf/dynamodb-admin:4.4.0
    container_name: usermanager_dynamodb-gui
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://usermanager_localstack:4566

  api-server:
    build:
      context: ../../
      dockerfile: Dockerfile.api
    image: usermanager_api
    container_name: usermanager_api
    environment:
      - USERMANAGER_S3_BUCKET=uibucket
      - USERMANAGER_SEARCH_INDEX_NAME=searchIndex
    ports:
      - "8989:8989"

