name: Update Web App

on:
  push:
    paths:
      - 'api/lambdas/user_manager/**'
  pull_request:
    branches: [ main ]

env:
  AWS_REGION : "ca-central-1"

defaults:
  run:
    working-directory: ./api/lambdas
  
permissions:
      id-token: write
      contents: read    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - name: build app
      run: |
        rm -rf ./bin
        env GOARCH=amd64 GOOS=linux $(which go) build -ldflags="-s -w" -o bin/bootstrap user_manager/main.go
        zip -mj bin/usermanager.zip bin/bootstrap     
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.USER_MANAGER_AWS_DEPLOY_ROLE_ARN }}
        role-session-name: githubdeploysession
        aws-region: ${{ env.AWS_REGION }}
    - name: update app
      run: |
        functionName=$(aws cloudformation describe-stacks --stack-name ${{ secrets.USER_MANAGER_AWS_STACK_NAME }} --query "Stacks[0].Outputs[?OutputKey=='UserManagerLambda'].OutputValue" | jq -r '.[0]')
        aws lambda update-function-code --function-name ${functionName} --zip-file fileb://bin/usermanager.zip


