name: Update Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AWS_REGION : "ca-central-1"

defaults:
  run:
    working-directory: ./ui/user-manager
  
permissions:
      id-token: write
      contents: read    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.13.0'
    - name: Build app
      run: |
        npm ci
        npm run build --if-present
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.USER_MANAGER_AWS_DEPLOY_ROLE_ARN }}
        role-session-name: githubdeploysession
        aws-region: ${{ env.AWS_REGION }}
    - name: update app
      run: |
        s3bucket=$(aws cloudformation describe-stacks --stack-name ${{ secrets.USER_MANAGER_AWS_STACK_NAME }} --profile personal --region ca-central-1 --query "Stacks[0].Outputs[?OutputKey=='WebAppBucketName'].OutputValue" | jq -r '.[0]')
        echo $s3bucket


